In [1]:
import pandas as pd


In [117]:
content=pd.read_csv('movie_comments.csv')

C:\Users\K\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [118]:
content.head()

id                                        link name  \
0  1  https://movie.douban.com/subject/26363254/  战狼2   
1  2  https://movie.douban.com/subject/26363254/  战狼2   
2  3  https://movie.douban.com/subject/26363254/  战狼2   
3  4  https://movie.douban.com/subject/26363254/  战狼2   
4  5  https://movie.douban.com/subject/26363254/  战狼2   

                                             comment star  
0                                 吴京意淫到了脑残的地步，看了恶心想吐    1  
1  首映礼看的。太恐怖了这个电影，不讲道理的，完全就是吴京在实现他这个小粉红的英雄梦。各种装备轮...    2  
2  吴京的炒作水平不输冯小刚，但小刚至少不会用主旋律来炒作…吴京让人看了不舒服，为了主旋律而主旋...    2  
3                      凭良心说，好看到不像《战狼1》的续集，完虐《湄公河行动》。    4  
4                                               中二得很    1

In [5]:
content.columns

Index(['id', 'link', 'name', 'comment', 'star'], dtype='object')

In [119]:
content['star'].unique()

array(['1', '2', '4', '5', '3', 'star', 4, 3, 5, 2, 1], dtype=object)

In [120]:
len(content)

261497

In [10]:
import re
def token3(string):
    # we will learn the regular expression next course.
    string2=string.replace('\\n','')
    
    return re.findall('\w+', string2) 
def cut(string):  # 加上去停用词
    a=list(jieba.cut(string))
    for index, word in enumerate(a) :
        if word in stop_words:
            del(a[index])
    return ' '.join(a)

In [11]:
#chinese_stopwords
file=open('chinese_stopwords.txt','r',encoding='utf-8')
stop=file.readlines()  
stop=[token3(n) for n in stop]
stop_words=[w[0] for w  in stop if len(w)>=1  ] 

In [13]:
len(stop_words)

508

In [15]:
temp_=content['comment'].astype('str').map(lambda x :token3(x))    

In [16]:
temp_

0                                     [吴京意淫到了脑残的地步, 看了恶心想吐]
1         [首映礼看的, 太恐怖了这个电影, 不讲道理的, 完全就是吴京在实现他这个小粉红的英雄梦, ...
2         [吴京的炒作水平不输冯小刚, 但小刚至少不会用主旋律来炒作, 吴京让人看了不舒服, 为了主旋...
3                        [凭良心说, 好看到不像, 战狼1, 的续集, 完虐, 湄公河行动]
4                                                    [中二得很]
5                              [犯我中华者, 虽远必诛, 吴京比这句话还要意淫一百倍]
6                                       [脑子是个好东西, 希望编剧们都能有]
7         [三星半, 实打实的7分, 第一集在爱国主旋律内部做着各种置换与较劲, 但第二集才真正显露吴...
8         [开篇长镜头惊险大气引人入胜, 结合了水平不俗的快剪下实打实的真刀真枪, 让人不禁热血沸腾,...
9         [15, 100吴京的冷峰在这部里即像成龙, 又像杰森斯坦森, 但体制外的同类型电影, 主角...
10                                  [犯我中华者虽远必诛, 是有多无脑才信这句话]
11              [这部戏让人看的热血沸腾, 对吴京路转粉, 最后的彩蛋, 让我们没有理由不期待下一部]
12                                            [假嗨, 特别恶心的电影]
13                            [有几处情节设置过于尴尬, 彰显国家自豪感的部分稍显突兀]
14        [就是一部爽片, 打戏挺燃, 但是故事一般, 达康书记不合适这个角色, 赵东来倒是很合适, ...
15        [赵东来, 达康书记, 我们接到在非洲卧底的冷锋报告, 丁义珍现在非洲, 我们请求抓捕, 李...
16                                   [下一

In [17]:
temp_=temp_.map(lambda x :"".join(x))  


In [18]:
temp_

0                                         吴京意淫到了脑残的地步看了恶心想吐
1         首映礼看的太恐怖了这个电影不讲道理的完全就是吴京在实现他这个小粉红的英雄梦各种装备轮番上场视...
2         吴京的炒作水平不输冯小刚但小刚至少不会用主旋律来炒作吴京让人看了不舒服为了主旋律而主旋律为了...
3                                    凭良心说好看到不像战狼1的续集完虐湄公河行动
4                                                      中二得很
5                                    犯我中华者虽远必诛吴京比这句话还要意淫一百倍
6                                           脑子是个好东西希望编剧们都能有
7         三星半实打实的7分第一集在爱国主旋律内部做着各种置换与较劲但第二集才真正显露吴京的野心他终于...
8         开篇长镜头惊险大气引人入胜结合了水平不俗的快剪下实打实的真刀真枪让人不禁热血沸腾特别弹簧床架...
9         15100吴京的冷峰在这部里即像成龙又像杰森斯坦森但体制外的同类型电影主角总是代表个人无能的...
10                                      犯我中华者虽远必诛是有多无脑才信这句话
11                      这部戏让人看的热血沸腾对吴京路转粉最后的彩蛋让我们没有理由不期待下一部
12                                                假嗨特别恶心的电影
13                                有几处情节设置过于尴尬彰显国家自豪感的部分稍显突兀
14        就是一部爽片打戏挺燃但是故事一般达康书记不合适这个角色赵东来倒是很合适张瀚太太太违和了分分钟...
15        赵东来达康书记我们接到在非洲卧底的冷锋报告丁义珍现在非洲我们请求抓捕李达康东来这件事先不要声...
16                                      

In [19]:
import jieba
temp_2=temp_.map(lambda x :cut(x)) 

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\K\AppData\Local\Temp\jieba.cache
Loading model cost 0.698 seconds.
Prefix dict has been built succesfully.


In [21]:
temp_2

0                                    吴京 意淫 了 脑残 地步 看 恶心 想 吐
1         首映礼 看 太 恐怖 这个 电影 不讲道理 完全 吴京 实现 这个 小 粉红 英雄 梦 装备...
2         吴京 炒作 水平 不输 冯小刚 但小刚 至少 不会 主旋律 炒作 吴京 人 看 不 舒服 主...
3                              凭良心说 看到 不像 战狼 的 续集 完虐 湄公河 行动
4                                                       中二得
5                              犯 中华 虽远必 诛 吴京 这句 话 还要 意淫 一百倍
6                                         脑子 个 东西 希望 编剧 都 有
7         三星 半 实打实 7 第一集 爱国 主旋律 内部 着 置换 较劲 第二集 才 真正 显露 吴...
8         开篇 长镜头 惊险 大气 引人入胜 结合 水平 不俗 快 剪下 实打实 真刀真枪 人 不禁 ...
9         15100 吴京 冷峰 这部 即 成龙 像杰 森斯坦 森但 体制 外 同 类型 电影 主角 ...
10                                 犯 中华 虽远必 诛 有 无脑 才 信 这句 话
11                这部 戏 人 看 热血沸腾 吴京路 转粉 最后 彩蛋 我们 没有 理由 期待 一部
12                                             假 嗨 特别 恶心 电影
13                        几处 情节 设置 过于 尴尬 彰显 国家 自豪感 部分 稍显 突兀
14        一部 爽片 打戏 挺燃 但是 故事 达康 书记 合适 角色 赵 东来 倒 很 合适 张瀚 太...
15        赵 东来 达康 书记 接到 非洲 卧底 冷锋 报告 丁义珍 现在 非洲 请求 抓捕 李达康 ...
16                                一部 拍 喜

In [22]:
content['star'].unique()

array(['1', '2', '4', '5', '3', 'star', 4, 3, 5, 2, 1], dtype=object)

In [23]:
content[content['star']=='star']

id  link  name  comment  star
568  id  link  name  comment  star

In [26]:
del(temp_2[568])

In [28]:
temp_2[569]

'盼 两年 火急火燎 全神贯注 地看 完后 吭爹 啊 除了 基佬 薰 必须 成一 坨 血 结局 外 这货 老版 TV AIR 毫无关系 吧 狗 链 无敌 高达 style 战舰 纤细 尾巴 糟点 各种 语焉不详 话 明白 死 似的 对白 我 智商 太低 实在 看不懂 啊 战斗 画面 棒 爆表脑 残 五星'

In [121]:
content.drop([568],inplace=True)

In [122]:
content['train']=temp_2

In [123]:
content.head()

id                                        link name  \
0  1  https://movie.douban.com/subject/26363254/  战狼2   
1  2  https://movie.douban.com/subject/26363254/  战狼2   
2  3  https://movie.douban.com/subject/26363254/  战狼2   
3  4  https://movie.douban.com/subject/26363254/  战狼2   
4  5  https://movie.douban.com/subject/26363254/  战狼2   

                                             comment star  \
0                                 吴京意淫到了脑残的地步，看了恶心想吐    1   
1  首映礼看的。太恐怖了这个电影，不讲道理的，完全就是吴京在实现他这个小粉红的英雄梦。各种装备轮...    2   
2  吴京的炒作水平不输冯小刚，但小刚至少不会用主旋律来炒作…吴京让人看了不舒服，为了主旋律而主旋...    2   
3                      凭良心说，好看到不像《战狼1》的续集，完虐《湄公河行动》。    4   
4                                               中二得很    1   

                                               train  
0                             吴京 意淫 了 脑残 地步 看 恶心 想 吐  
1  首映礼 看 太 恐怖 这个 电影 不讲道理 完全 吴京 实现 这个 小 粉红 英雄 梦 装备...  
2  吴京 炒作 水平 不输 冯小刚 但小刚 至少 不会 主旋律 炒作 吴京 人 看 不 舒服 主...  
3                       凭良心说 看到 不像 战狼 的 续集 完虐 湄公河 行动  
4                                                中二得

In [111]:
content['star'].unique()

array([1, 2, 4, 5, 3], dtype=object)

In [99]:
type(content['star'][0])

int

In [69]:
for i,item in enumerate(content['star']):
    content['star'][i]=int(item)
    

In [100]:
content['star'].unique()  

array([1, 2, 4, 5, 3], dtype=object)

In [92]:
content.head()

id                                        link name  \
0  1  https://movie.douban.com/subject/26363254/  战狼2   
1  2  https://movie.douban.com/subject/26363254/  战狼2   
2  3  https://movie.douban.com/subject/26363254/  战狼2   
3  4  https://movie.douban.com/subject/26363254/  战狼2   
4  5  https://movie.douban.com/subject/26363254/  战狼2   

                                             comment star  \
0                                 吴京意淫到了脑残的地步，看了恶心想吐    1   
1  首映礼看的。太恐怖了这个电影，不讲道理的，完全就是吴京在实现他这个小粉红的英雄梦。各种装备轮...    2   
2  吴京的炒作水平不输冯小刚，但小刚至少不会用主旋律来炒作…吴京让人看了不舒服，为了主旋律而主旋...    2   
3                      凭良心说，好看到不像《战狼1》的续集，完虐《湄公河行动》。    4   
4                                               中二得很    1   

                                               train  
0                             吴京 意淫 了 脑残 地步 看 恶心 想 吐  
1  首映礼 看 太 恐怖 这个 电影 不讲道理 完全 吴京 实现 这个 小 粉红 英雄 梦 装备...  
2  吴京 炒作 水平 不输 冯小刚 但小刚 至少 不会 主旋律 炒作 吴京 人 看 不 舒服 主...  
3                       凭良心说 看到 不像 战狼 的 续集 完虐 湄公河 行动  
4                                                中二得

In [104]:
data=content[['star','train']]

In [105]:
data.columns=['label','train']

In [102]:
new_data['star'].unique()

array([1, 2, 4, 5, 3, '5', '4', '3', '1', '2'], dtype=object)

In [ ]:
data.head()

In [110]:
content[['star','train']]['star'].unique()

array([1, 2, 4, 5, 3, '5', '4', '3', '1', '2'], dtype=object)

In [116]:
content['star'].unique()

array([1, 2, 4, 5, 3], dtype=object)

In [125]:
content['star'].unique()

array(['1', '2', '4', '5', '3', 4, 3, 5, 2, 1], dtype=object)

In [126]:
data=pd.DataFrame(columns=['train','label'])

In [127]:
data

Empty DataFrame
Columns: [train, label]
Index: []

In [129]:
data['train']=temp_2

In [130]:
data

train label
0                                  吴京 意淫 了 脑残 地步 看 恶心 想 吐   NaN
1       首映礼 看 太 恐怖 这个 电影 不讲道理 完全 吴京 实现 这个 小 粉红 英雄 梦 装备...   NaN
2       吴京 炒作 水平 不输 冯小刚 但小刚 至少 不会 主旋律 炒作 吴京 人 看 不 舒服 主...   NaN
3                            凭良心说 看到 不像 战狼 的 续集 完虐 湄公河 行动   NaN
4                                                     中二得   NaN
5                            犯 中华 虽远必 诛 吴京 这句 话 还要 意淫 一百倍   NaN
6                                       脑子 个 东西 希望 编剧 都 有   NaN
7       三星 半 实打实 7 第一集 爱国 主旋律 内部 着 置换 较劲 第二集 才 真正 显露 吴...   NaN
8       开篇 长镜头 惊险 大气 引人入胜 结合 水平 不俗 快 剪下 实打实 真刀真枪 人 不禁 ...   NaN
9       15100 吴京 冷峰 这部 即 成龙 像杰 森斯坦 森但 体制 外 同 类型 电影 主角 ...   NaN
10                               犯 中华 虽远必 诛 有 无脑 才 信 这句 话   NaN
11              这部 戏 人 看 热血沸腾 吴京路 转粉 最后 彩蛋 我们 没有 理由 期待 一部   NaN
12                                           假 嗨 特别 恶心 电影   NaN
13                      几处 情节 设置 过于 尴尬 彰显 国家 自豪感 部分 稍显 突兀   NaN
14      一部 爽片 打戏 挺燃 但是 故事 达康 书记 合适 角色 赵 东来 倒 很 合适 张瀚 太...   NaN
15      赵 东来 达康 书记 接到 非洲 卧底 冷锋 报告 丁义珍 现在 非洲 请求 抓捕 李达康 ...   NaN
16                              一部 拍 喜剧 吧 整个 片子 真 感觉 挺 搞笑   NaN
17                                    战狼 里 吴京 能 打 打 得 徐晓冬   NaN
18        心往 一处 想劲往 一处 使 能 实现 的 梦想 看吧 第一部 好太多 谢谢 美队 动作 指导   NaN
19                                              都 火 我 没见识   NaN
20      开头 水下 长 对决 戏可算 华语 电影 顶尖 存在 驱逐舰 导弹 坦克 商业片 这么 狂用...   NaN
21      用心 啊 吴京 导演 小看 了 确实 导演 下功夫 拉 片子 知道 借鉴 好 至于 大家 比...   NaN
22                            犯 中华 虽远必 诛 这句 话 一直 我 脑子里 回响   NaN
23                    片头 海里 那场 动作 戏看 完 呆 下去 太假 太 做作 提前 离场   NaN
24                        好看 这部 戏 人 看 热血沸腾 打戏 挺燃 吴京 演技 棒呆   NaN
25      符合 有钱 续集 反而 拍 差 一 放之四海而皆准 规律 场面 越做越 然而 伴随 各种 动...   NaN
26      喜欢 这部 片子 人 不是 装傻 真傻 真的 没有 别的 看 肯定 不会 选 这部 直 男癌...   NaN
27      整部 电影 延续 的 风格 热血 场面 1 的 大 打戏 动作 不错 吴京 挺 适合 演 军...   NaN
28                目瞪狗 呆 太 瘠薄 好看 中国 人牛 b 硬道理 隔壁 建军 大爷 没 爱国   NaN
29      战狼 的 动作 场景 战斗 装备 全线 升级 热血 打斗 动作 从头 打到 尾战 狼 游走 ...   NaN
...                                                   ...   ...
261467  bg 戏略 出戏 结尾 坑爹 不过 男主 真的 一双 漂亮 可爱 大 眼睛 啊 太萌 但是 ...   NaN
261468                                                  行   NaN
261469                                        无聊 拍摄 手法 GJ   NaN
261470                                    小男主 游泳 游得 真心 挺快   NaN
261471  Apr è savoirvucefilm à 2heures10moijesuisunpeu...   NaN
261472             第一 個 吻 美 不卑不亢 整體 感覺 良好 這是 比較 現實 年 輕 故事   NaN
261473                                      文森 忧郁 眼神 人 心疼   NaN
261474                             不错 最后 结尾 互相 追逐 那个 恶寒 啊   NaN
261475                                百度 云 居然 我存 这 片子 禁 哈   NaN
261476  话 法国 出 帅哥 法国人 喜欢 浪漫 冲着 片名 我点 犹豫 没有 看 少年 美不美 真 ...   NaN
261477             第一 個 吻 美 不卑不亢 整體 感覺 良好 這是 比較 現實 年 輕 故事   NaN
261478                                      文森 忧郁 眼神 人 心疼   NaN
261479                             不错 最后 结尾 互相 追逐 那个 恶寒 啊   NaN
261480                                百度 云 居然 我存 这 片子 禁 哈   NaN
261481  话 法国 出 帅哥 法国人 喜欢 浪漫 冲着 片名 我点 犹豫 没有 看 少年 美不美 真 ...   NaN
261482                                     生活 爱情 亲情 友情 选择   NaN
261483                                                一般般   NaN
261484                                        电影 可以 随便 看看   NaN
261485                                        到底 怎么 看 完 的   NaN
261486                               成长 烦恼 美型 少年 难以 看清 真相   NaN
261487                                            轻松 喜剧电影   NaN
261488                                        温暖 剧情 温暖 结局   NaN
261489                主角 都 好看 是 一个 碧 悲情 小女 主角 是 一段 十七岁 故事   NaN
261490                                           一切都是 爲 顏   NaN
261491          大概 看 总的来说 不错 其实 内心 十分 期待 男主 他 好友 发生 点 的 哎   NaN
261492                  内容 只能 一般 女性 角色 都 悲 催 啊 不过 男 猪脚 很帅   NaN
261493                      翘 三天 班 窝 家里 看小 基片 惹 手动 拜拜 gif   NaN
261494  喜欢 女主角 希腊 雕塑 的 面庞 身体 一部 同志 题材 电影 迷恋 女主角 好像 不 应该 吧   NaN
261495                                      冲着 颜值 可以 看 下去   NaN
261496             除了 主人公 不帅 女主挺 漂亮 之外 唯一 感觉 他 男朋友 真让人 恶心   NaN

[261496 rows x 2 columns]

In [131]:
data['label']=content['star'].astype('int')

In [133]:
data['label'].unique()

array([1, 2, 4, 5, 3], dtype=int64)

In [134]:
data

train  label
0                                  吴京 意淫 了 脑残 地步 看 恶心 想 吐      1
1       首映礼 看 太 恐怖 这个 电影 不讲道理 完全 吴京 实现 这个 小 粉红 英雄 梦 装备...      2
2       吴京 炒作 水平 不输 冯小刚 但小刚 至少 不会 主旋律 炒作 吴京 人 看 不 舒服 主...      2
3                            凭良心说 看到 不像 战狼 的 续集 完虐 湄公河 行动      4
4                                                     中二得      1
5                            犯 中华 虽远必 诛 吴京 这句 话 还要 意淫 一百倍      1
6                                       脑子 个 东西 希望 编剧 都 有      2
7       三星 半 实打实 7 第一集 爱国 主旋律 内部 着 置换 较劲 第二集 才 真正 显露 吴...      4
8       开篇 长镜头 惊险 大气 引人入胜 结合 水平 不俗 快 剪下 实打实 真刀真枪 人 不禁 ...      4
9       15100 吴京 冷峰 这部 即 成龙 像杰 森斯坦 森但 体制 外 同 类型 电影 主角 ...      1
10                               犯 中华 虽远必 诛 有 无脑 才 信 这句 话      1
11              这部 戏 人 看 热血沸腾 吴京路 转粉 最后 彩蛋 我们 没有 理由 期待 一部      4
12                                           假 嗨 特别 恶心 电影      1
13                      几处 情节 设置 过于 尴尬 彰显 国家 自豪感 部分 稍显 突兀      2
14      一部 爽片 打戏 挺燃 但是 故事 达康 书记 合适 角色 赵 东来 倒 很 合适 张瀚 太...      2
15      赵 东来 达康 书记 接到 非洲 卧底 冷锋 报告 丁义珍 现在 非洲 请求 抓捕 李达康 ...      5
16                              一部 拍 喜剧 吧 整个 片子 真 感觉 挺 搞笑      2
17                                    战狼 里 吴京 能 打 打 得 徐晓冬      3
18        心往 一处 想劲往 一处 使 能 实现 的 梦想 看吧 第一部 好太多 谢谢 美队 动作 指导      3
19                                              都 火 我 没见识      2
20      开头 水下 长 对决 戏可算 华语 电影 顶尖 存在 驱逐舰 导弹 坦克 商业片 这么 狂用...      4
21      用心 啊 吴京 导演 小看 了 确实 导演 下功夫 拉 片子 知道 借鉴 好 至于 大家 比...      4
22                            犯 中华 虽远必 诛 这句 话 一直 我 脑子里 回响      4
23                    片头 海里 那场 动作 戏看 完 呆 下去 太假 太 做作 提前 离场      1
24                        好看 这部 戏 人 看 热血沸腾 打戏 挺燃 吴京 演技 棒呆      4
25      符合 有钱 续集 反而 拍 差 一 放之四海而皆准 规律 场面 越做越 然而 伴随 各种 动...      2
26      喜欢 这部 片子 人 不是 装傻 真傻 真的 没有 别的 看 肯定 不会 选 这部 直 男癌...      2
27      整部 电影 延续 的 风格 热血 场面 1 的 大 打戏 动作 不错 吴京 挺 适合 演 军...      4
28                目瞪狗 呆 太 瘠薄 好看 中国 人牛 b 硬道理 隔壁 建军 大爷 没 爱国      1
29      战狼 的 动作 场景 战斗 装备 全线 升级 热血 打斗 动作 从头 打到 尾战 狼 游走 ...      4
...                                                   ...    ...
261467  bg 戏略 出戏 结尾 坑爹 不过 男主 真的 一双 漂亮 可爱 大 眼睛 啊 太萌 但是 ...      3
261468                                                  行      3
261469                                        无聊 拍摄 手法 GJ      3
261470                                    小男主 游泳 游得 真心 挺快      3
261471  Apr è savoirvucefilm à 2heures10moijesuisunpeu...      4
261472             第一 個 吻 美 不卑不亢 整體 感覺 良好 這是 比較 現實 年 輕 故事      3
261473                                      文森 忧郁 眼神 人 心疼      4
261474                             不错 最后 结尾 互相 追逐 那个 恶寒 啊      4
261475                                百度 云 居然 我存 这 片子 禁 哈      3
261476  话 法国 出 帅哥 法国人 喜欢 浪漫 冲着 片名 我点 犹豫 没有 看 少年 美不美 真 ...      3
261477             第一 個 吻 美 不卑不亢 整體 感覺 良好 這是 比較 現實 年 輕 故事      3
261478                                      文森 忧郁 眼神 人 心疼      4
261479                             不错 最后 结尾 互相 追逐 那个 恶寒 啊      4
261480                                百度 云 居然 我存 这 片子 禁 哈      3
261481  话 法国 出 帅哥 法国人 喜欢 浪漫 冲着 片名 我点 犹豫 没有 看 少年 美不美 真 ...      3
261482                                     生活 爱情 亲情 友情 选择      3
261483                                                一般般      3
261484                                        电影 可以 随便 看看      3
261485                                        到底 怎么 看 完 的      1
261486                               成长 烦恼 美型 少年 难以 看清 真相      4
261487                                            轻松 喜剧电影      4
261488                                        温暖 剧情 温暖 结局      3
261489                主角 都 好看 是 一个 碧 悲情 小女 主角 是 一段 十七岁 故事      5
261490                                           一切都是 爲 顏      3
261491          大概 看 总的来说 不错 其实 内心 十分 期待 男主 他 好友 发生 点 的 哎      3
261492                  内容 只能 一般 女性 角色 都 悲 催 啊 不过 男 猪脚 很帅      3
261493                      翘 三天 班 窝 家里 看小 基片 惹 手动 拜拜 gif      3
261494  喜欢 女主角 希腊 雕塑 的 面庞 身体 一部 同志 题材 电影 迷恋 女主角 好像 不 应该 吧      2
261495                                      冲着 颜值 可以 看 下去      3
261496             除了 主人公 不帅 女主挺 漂亮 之外 唯一 感觉 他 男朋友 真让人 恶心      3

[261496 rows x 2 colu

In [135]:
data.to_csv('movie_classiffier')

# 可以从以下开始

In [77]:
import pandas as pd
data=pd.read_csv('movie_classiffier')

In [90]:
data.columns

Index(['Unnamed: 0', 'train', 'label'], dtype='object')

In [93]:
data.drop(['Unnamed: 0'],axis=1,inplace=True)


In [88]:
data.drop?

In [94]:
from gensim.models import Word2Vec 
from gensim.models import word2vec 


In [95]:
model = Word2Vec.load("word2vec_final.model")

In [145]:
a=model.wv['吴京']

In [146]:
b=model.wv['看']

In [160]:
model.wv['真让人']

array([-0.02881435,  0.05484307, -0.10716566, -0.06642789,  0.04436979,
        0.03561519, -0.07613713, -0.06504113,  0.07858262, -0.01332086,
       -0.07637004, -0.1442222 , -0.00561335,  0.02604688,  0.05232959,
        0.10659917,  0.0062074 ,  0.01588558, -0.02166997, -0.079565  ,
        0.01643973, -0.02210834, -0.029157  , -0.05558513, -0.01001653,
       -0.02263297,  0.0737381 ,  0.06456605,  0.00596903,  0.00185818,
        0.09017719,  0.01489826, -0.09919663,  0.06635129,  0.10152754,
       -0.05406262,  0.07143274, -0.10508927,  0.04306671,  0.05721814,
        0.12560946, -0.0318749 , -0.05708444,  0.00783384,  0.09660515,
       -0.02521403, -0.01754882, -0.01317438,  0.02811467, -0.0007325 ,
       -0.00185844, -0.01212758, -0.02720867,  0.03416887, -0.02027383,
       -0.02725276, -0.00074606, -0.0366683 , -0.03419125, -0.07223152,
        0.1296939 ,  0.00247324, -0.04518258, -0.03825115,  0.02944725,
       -0.02613931, -0.03841798, -0.05490458, -0.01459516,  0.02

In [147]:
a+b

array([-2.1321611 , -0.60448456, -5.0140615 , -0.70165646, -1.4183434 ,
       -1.2569818 , -0.2854657 , -3.0339696 , -0.44495958, -0.9818405 ,
       -0.73193455, -1.7655672 ,  0.95328903,  0.76862794, -0.33902615,
        0.9930564 , -2.6139019 , -3.2209432 ,  0.16033572, -1.5031447 ,
        0.58253926, -0.3922149 , -1.1713603 , -2.9050648 , -0.9156967 ,
       -0.9442048 ,  1.4549594 , -0.16458833, -1.6961043 , -2.0942984 ,
        2.6697273 ,  0.34122813, -2.9156435 , -0.2125072 , -0.50371456,
       -1.6972817 ,  3.6242898 ,  2.0184782 , -0.5788887 , -2.4532416 ,
        0.47289544,  0.8340843 , -2.7142284 , -0.4719573 ,  2.5769799 ,
        0.35959804, -1.1962559 ,  1.1452563 ,  1.8393793 , -1.1332121 ,
        1.6583033 , -0.5848491 , -1.2004136 ,  2.4691246 , -1.5478556 ,
       -1.4260943 , -0.7213464 ,  1.0107722 ,  1.4585693 , -1.1197406 ,
        1.9691834 , -0.49083436, -0.4515501 , -2.072952  ,  1.2035128 ,
        0.13690153,  0.7931272 ,  0.05178583,  0.17138836, -3.41

In [174]:
a/2

array([ 1.23884186e-01, -5.57311773e-02, -6.45333603e-02, -6.73921257e-02,
        7.60020837e-02,  1.81752220e-01, -2.83826590e-01, -2.47357160e-01,
       -3.42043564e-02, -2.10853338e-01, -8.66561830e-02, -6.22019591e-03,
        1.61360040e-01,  2.76800215e-01,  2.85179675e-01,  1.43915042e-01,
       -7.50081837e-02, -1.37484238e-01,  5.43649532e-02, -1.79919913e-01,
        4.49529961e-02,  9.11388323e-02,  3.69756483e-02, -3.14831585e-01,
        6.18992038e-02,  5.12776757e-03,  9.45035089e-03,  6.52718842e-02,
        5.05897179e-02, -1.05034538e-01,  1.62284702e-01,  1.56402767e-01,
       -1.65868878e-01, -7.23225400e-02,  5.46090603e-01, -4.30692844e-02,
        1.36214629e-01,  1.22057749e-02, -8.46092328e-02,  1.15314558e-01,
       -7.77685409e-03,  1.03112273e-01, -1.42819256e-01, -5.08432239e-02,
       -9.55039933e-02, -6.42714053e-02, -2.74901241e-01,  3.38781513e-02,
       -1.85969964e-01, -2.52217054e-02,  6.62195217e-03,  1.95519850e-01,
        6.49433360e-02, -

In [205]:
import numpy as np
add=np.array([0]*200,dtype='float64')

In [204]:
model.wv['吴京']

array([ 2.47768372e-01, -1.11462355e-01, -1.29066721e-01, -1.34784251e-01,
        1.52004167e-01,  3.63504440e-01, -5.67653179e-01, -4.94714320e-01,
       -6.84087127e-02, -4.21706676e-01, -1.73312366e-01, -1.24403918e-02,
        3.22720081e-01,  5.53600430e-01,  5.70359349e-01,  2.87830085e-01,
       -1.50016367e-01, -2.74968475e-01,  1.08729906e-01, -3.59839827e-01,
        8.99059922e-02,  1.82277665e-01,  7.39512965e-02, -6.29663169e-01,
        1.23798408e-01,  1.02555351e-02,  1.89007018e-02,  1.30543768e-01,
        1.01179436e-01, -2.10069075e-01,  3.24569404e-01,  3.12805533e-01,
       -3.31737757e-01, -1.44645080e-01,  1.09218121e+00, -8.61385688e-02,
        2.72429258e-01,  2.44115498e-02, -1.69218466e-01,  2.30629116e-01,
       -1.55537082e-02,  2.06224546e-01, -2.85638511e-01, -1.01686448e-01,
       -1.91007987e-01, -1.28542811e-01, -5.49802482e-01,  6.77563027e-02,
       -3.71939927e-01, -5.04434109e-02,  1.32439043e-02,  3.91039699e-01,
        1.29886672e-01, -

In [201]:
add

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [101]:
data['train'][0].split()

['吴京', '意淫', '了', '脑残', '地步', '看', '恶心', '想', '吐']

In [ ]:
data.dropna(inplace=True)

In [111]:
def add_w2v(sent):
    add=np.array([0]*200,dtype='float64')
    for word in sent.split():
        try :
            add+=model.wv[word]
        except:
            #print('22')
            continue
    return add
        
         

In [123]:
add_w2v(data['train'][3])

array([ -2.73261937,   3.4649515 ,  -8.36280445,  -0.45983905,
         1.68594871,  -3.38501465,  -0.86078371,  -6.56022173,
         2.58052066,   6.46380156,  -3.31334749,  -5.91841099,
         4.2070503 ,   4.11223285,  -1.45109627,   4.8485923 ,
         3.08582542,  -0.05903597,  -6.13539158,   3.42023061,
        -6.25482261,   2.05421654,  -6.13422349,  -6.08076072,
        -0.21443968,   1.02876782,  -1.94082566,  -0.92655408,
        -7.56821297,  -3.14481592,   9.87506089,   2.69950825,
        -6.44629668,   3.1823691 ,  -3.39015056,  -1.05680631,
         6.24449375,  -0.83741595,   4.1350811 ,   5.65968564,
        -3.24480034,   1.18649067,   2.07897625,  -0.84287898,
         0.96324575,  -0.24119898,   5.49895525,  -0.52832888,
         2.79381103,   0.95701887,  -5.20503612,   5.56555712,
        -7.08028862,  -1.74095424,   4.56507429,   5.282936  ,
         0.55414407,   5.89756004,   3.92975613,   8.0917969 ,
         2.8097802 ,  -4.16474205,   0.50761713,   3.14

In [137]:
data_set=data.train.apply(lambda x: add_w2v(x))  

In [138]:
data_set

0         [-5.7669214606285095, 0.2759451474994421, -17....
1         [-14.853494452312589, -6.740517023950815, -39....
2         [-33.671623853966594, -19.632089510560036, -52...
3         [-2.7326193749904633, 3.4649515002965927, -8.3...
4         [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
5         [2.2739217206835747, -6.805470319464803, -3.87...
6         [-8.651657849550247, -9.46444673743099, -10.68...
7         [-17.254001160617918, 5.056470288778655, -31.2...
8         [-13.449447767576203, -3.6582538709044456, -59...
9         [-18.78183954767883, -8.672988922422519, -67.9...
10        [-1.8670595493167639, -7.652099639177322, -9.4...
11        [-11.048101752996445, -4.0228386372327805, -27...
12        [0.3773631453514099, -2.5096298791468143, -6.2...
13        [-3.8577968925237656, -5.168233800679445, -1.2...
14        [-8.805680349469185, -2.6432737335562706, -23....
15        [-14.14359913021326, -4.844545908272266, -36.0...
16        [2.7371866554021835, -2.168792

In [133]:
data.dropna(inplace=True)

In [221]:
data_set

0         [-5.7669214606285095, 0.2759451474994421, -17....
1         [-14.853494452312589, -6.740517023950815, -39....
2         [-33.671623853966594, -19.632089510560036, -52...
3         [-2.7326193749904633, 3.4649515002965927, -8.3...
4         [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
5         [2.2739217206835747, -6.805470319464803, -3.87...
6         [-8.651657849550247, -9.46444673743099, -10.68...
7         [-17.254001160617918, 5.056470288778655, -31.2...
8         [-13.449447767576203, -3.6582538709044456, -59...
9         [-18.78183954767883, -8.672988922422519, -67.9...
10        [-1.8670595493167639, -7.652099639177322, -9.4...
11        [-11.048101752996445, -4.0228386372327805, -27...
12        [0.3773631453514099, -2.5096298791468143, -6.2...
13        [-3.8577968925237656, -5.168233800679445, -1.2...
14        [-8.805680349469185, -2.6432737335562706, -23....
15        [-14.14359913021326, -4.844545908272266, -36.0...
16        [2.7371866554021835, -2.168792

In [139]:
raw=pd.DataFrame()

In [226]:
raw=pd.DataFrame(data_set)

In [227]:
raw

train
0       [-5.7669214606285095, 0.2759451474994421, -17....
1       [-14.853494452312589, -6.740517023950815, -39....
2       [-33.671623853966594, -19.632089510560036, -52...
3       [-2.7326193749904633, 3.4649515002965927, -8.3...
4       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
5       [2.2739217206835747, -6.805470319464803, -3.87...
6       [-8.651657849550247, -9.46444673743099, -10.68...
7       [-17.254001160617918, 5.056470288778655, -31.2...
8       [-13.449447767576203, -3.6582538709044456, -59...
9       [-18.78183954767883, -8.672988922422519, -67.9...
10      [-1.8670595493167639, -7.652099639177322, -9.4...
11      [-11.048101752996445, -4.0228386372327805, -27...
12      [0.3773631453514099, -2.5096298791468143, -6.2...
13      [-3.8577968925237656, -5.168233800679445, -1.2...
14      [-8.805680349469185, -2.6432737335562706, -23....
15      [-14.14359913021326, -4.844545908272266, -36.0...
16      [2.7371866554021835, -2.168792251497507, -18.7...
17      [1.166245136409998, -6.783718261867762, -14.11...
18      [-6.933631342835724, 9.386290401220322, -10.89...
19      [0.2603616714477539, -3.058043032884598, -9.56...
20      [-33.64093704428524, -9.555034982040524, -59.3...
21      [-38.56826934218407, -22.114401548169553, -70....
22      [2.278379086405039, -5.061468869447708, -11.42...
23      [-6.112397043034434, -5.295945145189762, -12.0...
24      [-2.995789811015129, -3.5794888883829117, -10....
25      [-31.576545561663806, -2.033128106035292, -47....
26      [-25.384845100343227, -0.6363431271165609, -49...
27      [-20.270544573664665, 9.89835124090314, -50.42...
28      [-3.255255847238004, 1.3819653941318393, -7.53...
29      [4.2519171833992, 4.146536662243307, -20.96698...
...                                                   ...
261467  [-23.34896326251328, -3.5928257033228874, -30....
261468  [-3.079564332962036, -1.653973937034607, 0.978...
261469  [1.5029511153697968, -0.7963184118270874, -6.9...
261470  [-0.10819741897284985, -0.8055463060736656, -2...
261471  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
261472  [-1.2131836786866188, 3.796048551797867, 1.173...
261473  [-1.3126720786094666, -0.6174640506505966, -4....
261474  [-4.4279750213027, -1.5515444539487362, -20.40...
261475  [1.162652499973774, 0.3345242887735367, -9.356...
261476  [-35.8552041919902, 6.979577148333192, -83.010...
261477  [-1.2131836786866188, 3.796048551797867, 1.173...
261478  [-1.3126720786094666, -0.6174640506505966, -4....
261479  [-4.4279750213027, -1.5515444539487362, -20.40...
261480  [1.162652499973774, 0.3345242887735367, -9.356...
261481  [-35.8552041919902, 6.979577148333192, -83.010...
261482  [4.744788885116577, -3.2558634877204895, -6.21...
261483  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
261484  [-5.54003518819809, -2.3005538061261177, -7.34...
261485  [-7.653102517127991, -0.9163336753845215, -14....
261486  [-2.348842915147543, 1.8177701905369759, -4.28...
261487  [1.3750323355197906, 1.2623395919799805, -1.92...
261488  [-0.9189026728272438, -6.079647362232208, -6.0...
261489  [-7.973951812833548, -2.8795939031988382, -14....
261490  [-1.7749154567718506, -0.009029976092278957, -...
261491  [-9.198717189952731, -1.2441844306886196, -31....
261492  [-5.884169191122055, -11.53183963149786, -14.3...
261493  [-1.646532028913498, -4.787015318870544, -5.50...
261494  [-4.791354291141033, 4.861815150827169, -25.30...
261495  [-6.607984345406294, -2.315675912424922, -10.2...
261496  [-9.322807373479009, -0.43694600835442543, -15...

[261496 rows x 1 columns]

In [140]:
raw=pd.DataFrame(columns=range(0,200),index=range(0,len(data_set)))

In [141]:
raw.columns

RangeIndex(start=0, stop=200, step=1)

In [142]:
raw

0    1    2    3    4    5    6    7    8    9   ...   190  191  192  \
0       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
1       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
2       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
3       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
4       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
5       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
6       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
7       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
8       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
9       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
10      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
11      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
12      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
13      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
14      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
15      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
16      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
17      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
18      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
19      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
20      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
21      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
22      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
23      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
24      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
25      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
26      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
27      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
28      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
29      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ...   ...  ...  ...   
260023  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260024  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260025  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260026  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260027  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260028  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260029  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260030  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260031  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260032  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260033  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260034  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260035  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260036  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260037  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260038  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260039  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260040  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN ...   NaN  NaN  NaN   
260041  

In [143]:
len(data_set)

260053

In [274]:
raw['label']=data['label']

In [275]:
raw

0         1          2          3         4         5  \
0      -5.76692  0.275945   -17.1309   -1.11131  0.722152  -5.86246   
1      -14.8535  -6.74052    -39.939   -2.01532   11.4631  -17.9868   
2      -33.6716  -19.6321    -52.115    6.70932   13.2816  -14.9803   
3      -2.73262   3.46495    -8.3628  -0.459839   1.68595  -3.38501   
4             0         0          0          0         0         0   
5       2.27392  -6.80547   -3.87078   0.908149   5.20789  -6.62462   
6      -8.65166  -9.46445   -10.6852    7.69643 -0.388712  -2.21566   
7       -17.254   5.05647   -31.2633    21.4761   12.6408  -21.4464   
8      -13.4494  -3.65825   -59.7715    19.3561   16.1305  -38.8179   
9      -18.7818  -8.67299   -67.9506    26.7495   12.9748  -23.2196   
10     -1.86706   -7.6521   -9.49103     4.6153   4.34195  -6.51589   
11     -11.0481  -4.02284   -27.4986   -3.80419 -0.874718  -12.1793   
12     0.377363  -2.50963   -6.21182     1.1855 -0.106422  -5.28797   
13      -3.8578  -5.16823   -1.22739    7.18782   1.16423 -0.671918   
14     -8.80568  -2.64327   -23.3859   0.775967   7.79017  -3.95664   
15     -14.1436  -4.84455   -36.0673   -9.12893   11.8135  -12.0183   
16      2.73719  -2.16879   -18.7782    3.56822   10.3696  -13.7012   
17      1.16625  -6.78372   -14.1143      3.954   9.00361   4.17513   
18     -6.93363   9.38629   -10.8955    4.20237 -0.708544  -8.98569   
19     0.260362  -3.05804   -9.56983    1.52523   1.84707  -4.74044   
20     -33.6409  -9.55503   -59.3127    14.7372    26.313  -7.25748   
21     -38.5683  -22.1144   -70.4812    29.4757   14.3347  -39.7933   
22      2.27838  -5.06147   -11.4205   -2.24033   10.5507  -8.76501   
23      -6.1124  -5.29595   -12.0136    -9.6009   4.30792   4.94721   
24     -2.99579  -3.57949    -10.333   -1.02309   2.61332  -4.97331   
25     -31.5765  -2.03313   -47.1207    13.7058   16.7477  -33.7661   
26     -25.3848 -0.636343   -49.5895   -1.19794   11.2738  -12.4756   
27     -20.2705   9.89835   -50.4283    15.9702   24.6592  -28.5039   
28     -3.25526   1.38197   -7.53276   -1.22049   3.78404   1.37361   
29      4.25192   4.14654    -20.967 -0.0742553    19.412  -17.9071   
...         ...       ...        ...        ...       ...       ...   
4970   -0.76762   3.07467   -1.26623    1.78409   -0.3501  0.266847   
4971   -11.9682  -1.86762   -16.9742    7.08654   3.42955  -5.28279   
4972   -12.1129  0.938823    -73.941   -9.52993   10.1382  -24.1886   
4973  0.0877292   1.90306   -5.21289   -2.68442      2.17  -5.02684   
4974   0.521192   3.05748   0.412678  -0.490963   2.17509   1.19322   
4975   -49.0578  -10.1859   -61.8568    15.4119   25.8796  -26.5457   
4976   0.522917 -0.394345   0.926856  -0.944131  0.331905  0.621169   
4977  -0.964998  -4.07606   -11.1079    1.85671 -0.833095 -0.200527   
4978   -12.1209 -0.649597   -35.2212    15.1823   12.8669  -14.5623   
4979          0         0          0          0         0         0   
4980          0         0          0          0         0         0   
4981   -5.15166  -4.07872   -7.10762    3.08258   1.44579  -5.94378   
4982   0.181608  -0.92128   -18.3771    2.39824  -6.26257  -10.7301   
4983  -0.218573   1.04604   -5.14604  -0.807275   2.88585  -3.93329   
4984    -25.481  -3.48936   -54.9704  -0.768823  0.950168  -19.4457   
4985   -7.20362   4.82198   -21.0698 -0.0941463   3.82013  -16.4827   
4986  -0.765728  -1.11479 -0.0538834  -0.434883   0.35971   2.43758   
4987   -3.48501  -0.83766   -3.62878  -0.617579  0.108014 -0.135858   
4988    -3.4582   1.16279    -8.2879   -1.32289   3.29087  -7.12916   
4989  -0.218573   1.04604   -5.14604  -0.807275   2.88585  -3.93329   
4990    -25.481  -3.48936   -54.9704  -0.768823  0.950168  -19.4457   
4991   -7.20362   4.82198   -21.0698 -0.0941463   3.82013  -16.4827   
4992  -0.765728  -1.11479 -0.0538834  -0.434883   0.35971   2.43758   
4993   -3.48501  -0.83766   -3.62878  -0.617579  0.108014 -0.135858   
4994    -3.4582   1.16279    -8.2879  

In [283]:

for i in range(len(raw2)):
    if all(raw2.loc[i][:-1])==0:
        raw2.drop([i],inplace=True)
        
        
    

In [276]:
raw2=raw.copy()

In [286]:
raw2.reset_index(inplace=True)

# 清洗好的数据

In [7]:
import joblib

In [8]:
data=joblib.load('train_data.pkl')

In [9]:
data.shape

(10000, 200)

In [10]:
import pandas as pd
raw_data=pd.read_csv('movie_classiffier')

In [11]:
raw_data

Unnamed: 0                                              train  label
0                0                             吴京 意淫 了 脑残 地步 看 恶心 想 吐      1
1                1  首映礼 看 太 恐怖 这个 电影 不讲道理 完全 吴京 实现 这个 小 粉红 英雄 梦 装备...      2
2                2  吴京 炒作 水平 不输 冯小刚 但小刚 至少 不会 主旋律 炒作 吴京 人 看 不 舒服 主...      2
3                3                       凭良心说 看到 不像 战狼 的 续集 完虐 湄公河 行动      4
4                4                                                中二得      1
5                5                       犯 中华 虽远必 诛 吴京 这句 话 还要 意淫 一百倍      1
6                6                                  脑子 个 东西 希望 编剧 都 有      2
7                7  三星 半 实打实 7 第一集 爱国 主旋律 内部 着 置换 较劲 第二集 才 真正 显露 吴...      4
8                8  开篇 长镜头 惊险 大气 引人入胜 结合 水平 不俗 快 剪下 实打实 真刀真枪 人 不禁 ...      4
9                9  15100 吴京 冷峰 这部 即 成龙 像杰 森斯坦 森但 体制 外 同 类型 电影 主角 ...      1
10              10                           犯 中华 虽远必 诛 有 无脑 才 信 这句 话      1
11              11          这部 戏 人 看 热血沸腾 吴京路 转粉 最后 彩蛋 我们 没有 理由 期待 一部      4
12              12                                       假 嗨 特别 恶心 电影      1
13              13                  几处 情节 设置 过于 尴尬 彰显 国家 自豪感 部分 稍显 突兀      2
14              14  一部 爽片 打戏 挺燃 但是 故事 达康 书记 合适 角色 赵 东来 倒 很 合适 张瀚 太...      2
15              15  赵 东来 达康 书记 接到 非洲 卧底 冷锋 报告 丁义珍 现在 非洲 请求 抓捕 李达康 ...      5
16              16                          一部 拍 喜剧 吧 整个 片子 真 感觉 挺 搞笑      2
17              17                                战狼 里 吴京 能 打 打 得 徐晓冬      3
18              18    心往 一处 想劲往 一处 使 能 实现 的 梦想 看吧 第一部 好太多 谢谢 美队 动作 指导      3
19              19                                          都 火 我 没见识      2
20              20  开头 水下 长 对决 戏可算 华语 电影 顶尖 存在 驱逐舰 导弹 坦克 商业片 这么 狂用...      4
21              21  用心 啊 吴京 导演 小看 了 确实 导演 下功夫 拉 片子 知道 借鉴 好 至于 大家 比...      4
22              22                        犯 中华 虽远必 诛 这句 话 一直 我 脑子里 回响      4
23              23                片头 海里 那场 动作 戏看 完 呆 下去 太假 太 做作 提前 离场      1
24              24                    好看 这部 戏 人 看 热血沸腾 打戏 挺燃 吴京 演技 棒呆      4
25              25  符合 有钱 续集 反而 拍 差 一 放之四海而皆准 规律 场面 越做越 然而 伴随 各种 动...      2
26              26  喜欢 这部 片子 人 不是 装傻 真傻 真的 没有 别的 看 肯定 不会 选 这部 直 男癌...      2
27              27  整部 电影 延续 的 风格 热血 场面 1 的 大 打戏 动作 不错 吴京 挺 适合 演 军...      4
28              28            目瞪狗 呆 太 瘠薄 好看 中国 人牛 b 硬道理 隔壁 建军 大爷 没 爱国      1
29              29  战狼 的 动作 场景 战斗 装备 全线 升级 热血 打斗 动作 从头 打到 尾战 狼 游走 ...      4
...            ...                                                ...    ...
261466      261467  bg 戏略 出戏 结尾 坑爹 不过 男主 真的 一双 漂亮 可爱 大 眼睛 啊 太萌 但是 ...      3
261467      261468                                                  行      3
261468      261469                                        无聊 拍摄 手法 GJ      3
261469      261470                                    小男主 游泳 游得 真心 挺快      3
261470      261471  Apr è savoirvucefilm à 2heures10moijesuisunpeu...      4
261471      261472             第一 個 吻 美 不卑不亢 整體 感覺 良好 這是 比較 現實 年 輕 故事      3
261472      261473                                      文森 忧郁 眼神 人 心疼      4
261473      261474                             不错 最后 结尾 互相 追逐 那个 恶寒 啊      4
261474      261475                                百度 云 居然 我存 这 片子 禁 哈      3
261475      261476  话 法国 出 帅哥 法国人 喜欢 浪漫 冲着 片名 我点 犹豫 没有 看 少年 美不美 真 ...      3
261476      261477             第一 個 吻 美 不卑不亢 整體 感覺 良好 這是 比較 現實 年 輕 故事      3
261477      261478                                      文森 忧郁 眼神 人 心疼      4
261478      261479                             不错 最后 结尾 互相 追逐 那个 恶寒 啊      4
261479      261480                                百度 云 居然 我存 这 片子 禁 哈      3
261480      261481  话 法国 出 帅哥 法国人 喜欢 浪漫 冲着 片名 我点 犹豫 没有 看 少年 美不美 真 ...      3
261481      261482                                     生活 爱情 亲情 友情 选择      3
261482      261483                                                一般般      3
261483      261484                                        电影 可以 随便 看看      3
261484      261485                                        到底 怎么 看 完 的      1
261485      261486                               成长 烦恼 美型 少年 难以 看清 真相      4
2614

In [12]:
raw_data.drop(['Unnamed: 0'],axis=1,inplace=True)
raw_data.dropna(inplace=True)

In [14]:
raw_data.shape

(260053, 2)

In [16]:
data['label']=raw_data['label'][:data.shape[0]]

In [17]:
data

0         1         2          3           4          5  \
0      -5.76692  0.275945  -17.1309   -1.11131    0.722152   -5.86246   
1      -14.8535  -6.74052   -39.939   -2.01532     11.4631   -17.9868   
2      -33.6716  -19.6321   -52.115    6.70932     13.2816   -14.9803   
3      -2.73262   3.46495   -8.3628  -0.459839     1.68595   -3.38501   
4             0         0         0          0           0          0   
5       2.27392  -6.80547  -3.87078   0.908149     5.20789   -6.62462   
6      -8.65166  -9.46445  -10.6852    7.69643   -0.388712   -2.21566   
7       -17.254   5.05647  -31.2633    21.4761     12.6408   -21.4464   
8      -13.4494  -3.65825  -59.7715    19.3561     16.1305   -38.8179   
9      -18.7818  -8.67299  -67.9506    26.7495     12.9748   -23.2196   
10     -1.86706   -7.6521  -9.49103     4.6153     4.34195   -6.51589   
11     -11.0481  -4.02284  -27.4986   -3.80419   -0.874718   -12.1793   
12     0.377363  -2.50963  -6.21182     1.1855   -0.106422   -5.28797   
13      -3.8578  -5.16823  -1.22739    7.18782     1.16423  -0.671918   
14     -8.80568  -2.64327  -23.3859   0.775967     7.79017   -3.95664   
15     -14.1436  -4.84455  -36.0673   -9.12893     11.8135   -12.0183   
16      2.73719  -2.16879  -18.7782    3.56822     10.3696   -13.7012   
17      1.16625  -6.78372  -14.1143      3.954     9.00361    4.17513   
18     -6.93363   9.38629  -10.8955    4.20237   -0.708544   -8.98569   
19     0.260362  -3.05804  -9.56983    1.52523     1.84707   -4.74044   
20     -33.6409  -9.55503  -59.3127    14.7372      26.313   -7.25748   
21     -38.5683  -22.1144  -70.4812    29.4757     14.3347   -39.7933   
22      2.27838  -5.06147  -11.4205   -2.24033     10.5507   -8.76501   
23      -6.1124  -5.29595  -12.0136    -9.6009     4.30792    4.94721   
24     -2.99579  -3.57949   -10.333   -1.02309     2.61332   -4.97331   
25     -31.5765  -2.03313  -47.1207    13.7058     16.7477   -33.7661   
26     -25.3848 -0.636343  -49.5895   -1.19794     11.2738   -12.4756   
27     -20.2705   9.89835  -50.4283    15.9702     24.6592   -28.5039   
28     -3.25526   1.38197  -7.53276   -1.22049     3.78404    1.37361   
29      4.25192   4.14654   -20.967 -0.0742553      19.412   -17.9071   
...         ...       ...       ...        ...         ...        ...   
9970   -3.01064   -3.3133   -12.334   -3.68751     4.79684   -2.12405   
9971   -3.01064   -3.3133   -12.334   -3.68751     4.79684   -2.12405   
9972   -14.9151  -13.3199  -29.6386   -11.3515   -0.153689  -0.334863   
9973   -5.48325  -1.21167  -5.33071   0.276113    0.542866  -0.606087   
9974   -0.24687   1.15489  -17.5048   -5.71614     12.9828   -11.3312   
9975   -5.61248  0.986735  -24.8701    5.80847     5.99205   -14.5265   
9976   -7.53471  -16.3618  -22.3433    2.81985     7.44437   -4.35584   
9977          0         0         0          0           0          0   
9978   -4.76218  -0.24642  -4.26796    4.48664     2.08424   -1.28702   
9979    4.00793  -4.24798  -6.05563   -2.35456       4.912   -2.22912   
9980   -29.3605    2.4819  -79.0287   -2.13541     22.0025   -40.2209   
9981    1.53232  0.580589  -4.58407  -0.243164     3.57052   -2.09187   
9982   -14.3022 -0.678895   -13.722    4.91205     6.47218   -6.56753   
9983  0.0766549  -1.06962  -7.74279   -4.08848     6.67373   -1.12841   
9984   -3.23812   3.40279  -11.1098   -2.55868    -4.27721   -6.54177   
9985   -3.76448  0.523723  -22.5774  -0.734259     8.49424   -3.78622   
9986   -56.1261  -21.7826  -61.3066     17.104     35.2211   -24.5413   
9987   -25.3358  -8.37899  -28.0151    6.11194     7.10848   -18.4145   
9988    -14.817  -10.3837  -28.5058   -0.39979     4.29044   -11.5988   
9989   -32.8056  -4.48733  -44.2776    3.98876     16.5888   -3.22499   
9990   -1.11293  0.829512 -0.885645   -1.46639  0.00236497    1.39586   
9991    -1.9042  0.198287  -3.87626    4.10571     4.31856  0.0355662   
9992   -2.18339  -1.96101  -7.01335    1.81592   -0.445803   -1.07786   

In [18]:
for i in range(len(data)):
    if all(data.loc[i][:-1])==0:
        data.drop([i],inplace=True)
        
        
    

In [27]:
data.label.unique()

array([ 1.,  2.,  4.,  5.,  3., nan])

In [28]:
data.dropna(inplace=True)

In [29]:
data.label.unique()

array([1., 2., 4., 5., 3.])

In [ ]:
def label_()

In [32]:
data.label=data.label.apply(lambda x:x-1)

In [33]:
data.label.unique()

array([0., 1., 3., 4., 2.])

In [60]:
data=data.reset_index()

In [68]:
data.drop(['index'],axis=1,inplace=True)

In [76]:
data

0         1         2          3           4          5  \
0      -5.76692  0.275945  -17.1309   -1.11131    0.722152   -5.86246   
1      -14.8535  -6.74052   -39.939   -2.01532     11.4631   -17.9868   
2      -33.6716  -19.6321   -52.115    6.70932     13.2816   -14.9803   
3      -2.73262   3.46495   -8.3628  -0.459839     1.68595   -3.38501   
4       2.27392  -6.80547  -3.87078   0.908149     5.20789   -6.62462   
5      -8.65166  -9.46445  -10.6852    7.69643   -0.388712   -2.21566   
6       -17.254   5.05647  -31.2633    21.4761     12.6408   -21.4464   
7      -13.4494  -3.65825  -59.7715    19.3561     16.1305   -38.8179   
8      -18.7818  -8.67299  -67.9506    26.7495     12.9748   -23.2196   
9      -1.86706   -7.6521  -9.49103     4.6153     4.34195   -6.51589   
10     -11.0481  -4.02284  -27.4986   -3.80419   -0.874718   -12.1793   
11     0.377363  -2.50963  -6.21182     1.1855   -0.106422   -5.28797   
12      -3.8578  -5.16823  -1.22739    7.18782     1.16423  -0.671918   
13     -8.80568  -2.64327  -23.3859   0.775967     7.79017   -3.95664   
14     -14.1436  -4.84455  -36.0673   -9.12893     11.8135   -12.0183   
15      2.73719  -2.16879  -18.7782    3.56822     10.3696   -13.7012   
16      1.16625  -6.78372  -14.1143      3.954     9.00361    4.17513   
17     -6.93363   9.38629  -10.8955    4.20237   -0.708544   -8.98569   
18     0.260362  -3.05804  -9.56983    1.52523     1.84707   -4.74044   
19     -33.6409  -9.55503  -59.3127    14.7372      26.313   -7.25748   
20     -38.5683  -22.1144  -70.4812    29.4757     14.3347   -39.7933   
21      2.27838  -5.06147  -11.4205   -2.24033     10.5507   -8.76501   
22      -6.1124  -5.29595  -12.0136    -9.6009     4.30792    4.94721   
23     -2.99579  -3.57949   -10.333   -1.02309     2.61332   -4.97331   
24     -31.5765  -2.03313  -47.1207    13.7058     16.7477   -33.7661   
25     -25.3848 -0.636343  -49.5895   -1.19794     11.2738   -12.4756   
26     -20.2705   9.89835  -50.4283    15.9702     24.6592   -28.5039   
27     -3.25526   1.38197  -7.53276   -1.22049     3.78404    1.37361   
28      4.25192   4.14654   -20.967 -0.0742553      19.412   -17.9071   
29     -26.7335  -18.3234  -53.5376     11.502     3.38526   -23.6297   
...         ...       ...       ...        ...         ...        ...   
9706   -2.26844    1.0092  -8.49388    6.33935     6.19646   -4.40944   
9707   -3.01064   -3.3133   -12.334   -3.68751     4.79684   -2.12405   
9708   -3.01064   -3.3133   -12.334   -3.68751     4.79684   -2.12405   
9709   -14.9151  -13.3199  -29.6386   -11.3515   -0.153689  -0.334863   
9710   -5.48325  -1.21167  -5.33071   0.276113    0.542866  -0.606087   
9711   -0.24687   1.15489  -17.5048   -5.71614     12.9828   -11.3312   
9712   -5.61248  0.986735  -24.8701    5.80847     5.99205   -14.5265   
9713   -7.53471  -16.3618  -22.3433    2.81985     7.44437   -4.35584   
9714   -4.76218  -0.24642  -4.26796    4.48664     2.08424   -1.28702   
9715    4.00793  -4.24798  -6.05563   -2.35456       4.912   -2.22912   
9716   -29.3605    2.4819  -79.0287   -2.13541     22.0025   -40.2209   
9717    1.53232  0.580589  -4.58407  -0.243164     3.57052   -2.09187   
9718   -14.3022 -0.678895   -13.722    4.91205     6.47218   -6.56753   
9719  0.0766549  -1.06962  -7.74279   -4.08848     6.67373   -1.12841   
9720   -3.23812   3.40279  -11.1098   -2.55868    -4.27721   -6.54177   
9721   -3.76448  0.523723  -22.5774  -0.734259     8.49424   -3.78622   
9722   -56.1261  -21.7826  -61.3066     17.104     35.2211   -24.5413   
9723   -25.3358  -8.37899  -28.0151    6.11194     7.10848   -18.4145   
9724    -14.817  -10.3837  -28.5058   -0.39979     4.29044   -11.5988   
9725   -32.8056  -4.48733  -44.2776    3.98876     16.5888   -3.22499   
9726   -1.11293  0.829512 -0.885645   -1.46639  0.00236497    1.39586   
9727    -1.9042  0.198287  -3.87626    4.10571     4.31856  0.0355662   
9728   -2.18339  -1.96101  -7.01335    1.81592   -0.445803   -1.07786   

In [ ]:
data[]

In [75]:
data.shape


(9736, 201)

In [78]:
train_dataset,train_labels=data.iloc[:9000,:-1],data.iloc[:9000,-1]
valid_dataset,valid_labels=data.iloc[9000:9000+430,:-1],data.iloc[9000:9000+430,-1]
test_dataset,test_labels=data.iloc[9000+430:,:-1],data.iloc[9000+430:,-1]
print('Training set', train_dataset.shape, train_labels.shape)
print('Validation set', valid_dataset.shape, valid_labels.shape)
print('Test set', test_dataset.shape, test_labels.shape)

Training set (9000, 200) (9000,)
Validation set (430, 200) (430,)
Test set (306, 200) (306,)


In [79]:
train_dataset

0          1          2          3          4          5    \
0      -5.76692   0.275945   -17.1309   -1.11131   0.722152   -5.86246   
1      -14.8535   -6.74052    -39.939   -2.01532    11.4631   -17.9868   
2      -33.6716   -19.6321    -52.115    6.70932    13.2816   -14.9803   
3      -2.73262    3.46495    -8.3628  -0.459839    1.68595   -3.38501   
4       2.27392   -6.80547   -3.87078   0.908149    5.20789   -6.62462   
5      -8.65166   -9.46445   -10.6852    7.69643  -0.388712   -2.21566   
6       -17.254    5.05647   -31.2633    21.4761    12.6408   -21.4464   
7      -13.4494   -3.65825   -59.7715    19.3561    16.1305   -38.8179   
8      -18.7818   -8.67299   -67.9506    26.7495    12.9748   -23.2196   
9      -1.86706    -7.6521   -9.49103     4.6153    4.34195   -6.51589   
10     -11.0481   -4.02284   -27.4986   -3.80419  -0.874718   -12.1793   
11     0.377363   -2.50963   -6.21182     1.1855  -0.106422   -5.28797   
12      -3.8578   -5.16823   -1.22739    7.18782    1.16423  -0.671918   
13     -8.80568   -2.64327   -23.3859   0.775967    7.79017   -3.95664   
14     -14.1436   -4.84455   -36.0673   -9.12893    11.8135   -12.0183   
15      2.73719   -2.16879   -18.7782    3.56822    10.3696   -13.7012   
16      1.16625   -6.78372   -14.1143      3.954    9.00361    4.17513   
17     -6.93363    9.38629   -10.8955    4.20237  -0.708544   -8.98569   
18     0.260362   -3.05804   -9.56983    1.52523    1.84707   -4.74044   
19     -33.6409   -9.55503   -59.3127    14.7372     26.313   -7.25748   
20     -38.5683   -22.1144   -70.4812    29.4757    14.3347   -39.7933   
21      2.27838   -5.06147   -11.4205   -2.24033    10.5507   -8.76501   
22      -6.1124   -5.29595   -12.0136    -9.6009    4.30792    4.94721   
23     -2.99579   -3.57949    -10.333   -1.02309    2.61332   -4.97331   
24     -31.5765   -2.03313   -47.1207    13.7058    16.7477   -33.7661   
25     -25.3848  -0.636343   -49.5895   -1.19794    11.2738   -12.4756   
26     -20.2705    9.89835   -50.4283    15.9702    24.6592   -28.5039   
27     -3.25526    1.38197   -7.53276   -1.22049    3.78404    1.37361   
28      4.25192    4.14654    -20.967 -0.0742553     19.412   -17.9071   
29     -26.7335   -18.3234   -53.5376     11.502    3.38526   -23.6297   
...         ...        ...        ...        ...        ...        ...   
8970   -5.83573   -7.55616   -32.0704   -4.13781    7.78417   -4.12832   
8971   -2.57077    4.77928   -13.7493    7.67417    5.07675   -9.25426   
8972    3.48571   -3.85119   0.481708   -1.23903  -0.583759   0.135031   
8973   0.260225   -4.58826   -17.4258  -0.363013    4.18639   -6.26122   
8974   -1.57452    1.72431   -4.30867     1.3161    2.29886   -4.46113   
8975   -16.4479   -3.98881   -44.5998      4.111    14.3228   -13.4254   
8976   -22.6871   -3.71751   -30.0736   0.157815    2.84414   -16.8707   
8977    -21.389   -1.71627   -30.3872   -2.59438    17.8844   -3.99696   
8978   -8.80905    4.18891   -13.4776    5.39897    3.29389   -1.30344   
8979   -31.4796   -9.73584   -56.3958    3.63615    8.74012   -18.0254   
8980    0.14911 -0.0870384  0.0131179 -0.0803522  0.0970628  0.0577362   
8981  -0.915693   0.936423   -1.43653 -0.0784416  -0.717421   -0.48435   
8982   -23.9448   -12.9739   -30.1189   -1.24782    5.97356   -15.8317   
8983   -12.1582   -7.10114   -33.2156     13.235     19.512   -1.83231   
8984   -29.8311   -19.7156   -27.2137    1.84407   -2.52198   -6.54822   
8985   -34.7797    6.54163   -73.8604    25.2475    10.5873   -22.8237   
8986  -0.523689    0.71591    -9.4638    1.92793   0.588791   -2.49052   
8987   -3.01266   -1.63249   -6.67542   -1.36452  -0.971014   -3.27787   
8988   -16.2041   -19.5379   -15.9479   -1.92329    4.83336   -1.64283   
8989   -6.08623   -7.27294    2.49213    9.57204    2.60704   0.612661   
8990    1.05696    2.72751   -7.31881   0.238778    9.51588  -0.816414   
8991   -7.04241   -1.45647   -11.5455   0.294478    7.28221    -5.2932   
8992  -0.445336 

In [38]:
train_labels.unique()

array([0., 1., 3., 4., 2.])

In [40]:
import tensorflow as tf 

C:\Users\K\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [120]:
tf.reset_default_graph()


# 4个隐藏层
n_inputs =200 # MNIST
n_hidden1 = 300
n_hidden2 = 300
n_hidden3=200
n_hidden4=100

n_outputs = 5

X = tf.placeholder(tf.float32, shape=(None, n_inputs), name="X")
y = tf.placeholder(tf.int32, shape=(None), name="y")

In [116]:
scale = 0.001 # 惩罚系数

In [117]:
from functools import partial

In [118]:
my_dense_layer = partial(
    tf.layers.dense, activation=tf.nn.relu,
    kernel_regularizer=tf.contrib.layers.l1_regularizer(scale))    # l1惩罚

with tf.name_scope("dnn"):
    hidden1 = my_dense_layer(X, n_hidden1, name="hidden1")
    hidden2 = my_dense_layer(hidden1, n_hidden2, name="hidden2")
    hidden3 = my_dense_layer(hidden2, n_hidden3, name="hidden3")
    hidden4 = my_dense_layer(hidden3, n_hidden4, name="hidden4")
             
    logits = my_dense_layer(hidden4, n_outputs, activation=None,
                            name="outputs")
with tf.name_scope("loss"):                                     # not shown in the book
    xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(  # not shown
        labels=y, logits=logits)                                # not shown
    base_loss = tf.reduce_mean(xentropy, name="avg_xentropy")   # not shown
    reg_losses = tf.get_collection(tf.GraphKeys.REGULARIZATION_LOSSES)
    loss = tf.add_n([base_loss] + reg_losses, name="loss")
with tf.name_scope("eval"):
    correct = tf.nn.in_top_k(logits, y, 1)
    accuracy = tf.reduce_mean(tf.cast(correct, tf.float32), name="accuracy")

learning_rate = 0.01

with tf.name_scope("train"):
    optimizer = tf.train.GradientDescentOptimizer(learning_rate)
    training_op = optimizer.minimize(loss)

init = tf.global_variables_initializer()
saver = tf.train.Saver()

In [112]:
import numpy as np
def shuffle_batch(X, y, batch_size):
    rnd_idx = np.random.permutation(len(X))
    #print( rnd_idx )
    n_batches = len(X) // batch_size
    for batch_idx in np.array_split(rnd_idx, n_batches):
        X_batch, y_batch = X[batch_idx], y[batch_idx]
        yield X_batch, y_batch

In [94]:
type(train_dataset)

pandas.core.frame.DataFrame

In [101]:
np.array(train_dataset).shape

(9000, 200)

In [103]:
batch_size

200

In [105]:
shuffle_batch(np.array(train_dataset),np.array(train_labels), batch_size)

<generator object shuffle_batch at 0x0000020B02C7CC50>

In [119]:
n_epochs = 100
batch_size = 500
X_valid,  y_valid=np.array(valid_dataset),np.array(valid_labels)

with tf.Session() as sess:
    init.run()
    for epoch in range(n_epochs):
        for X_batch, y_batch in shuffle_batch(np.array(train_dataset),np.array(train_labels), batch_size):
            sess.run(training_op, feed_dict={X: X_batch, y: y_batch})
        accuracy_val = accuracy.eval(feed_dict={X: X_valid, y: y_valid})
        print(epoch, "Validation accuracy:", accuracy_val)

 #   save_path = saver.save(sess, "./my_model_final.ckpt")

0 Validation accuracy: 0.29767442
1 Validation accuracy: 0.28139535
2 Validation accuracy: 0.29302326
3 Validation accuracy: 0.2883721
4 Validation accuracy: 0.29069766
5 Validation accuracy: 0.29302326
6 Validation accuracy: 0.2860465
7 Validation accuracy: 0.28372094
8 Validation accuracy: 0.3
9 Validation accuracy: 0.29069766
10 Validation accuracy: 0.29069766
11 Validation accuracy: 0.29767442
12 Validation accuracy: 0.30697674
13 Validation accuracy: 0.3
14 Validation accuracy: 0.29767442
15 Validation accuracy: 0.29767442
16 Validation accuracy: 0.31627908
17 Validation accuracy: 0.2860465
18 Validation accuracy: 0.3116279
19 Validation accuracy: 0.30697674
20 Validation accuracy: 0.30232558
21 Validation accuracy: 0.3116279
22 Validation accuracy: 0.30232558
23 Validation accuracy: 0.3139535
24 Validation accuracy: 0.30232558
25 Validation accuracy: 0.3116279
26 Validation accuracy: 0.30930233
27 Validation accuracy: 0.30465117
28 Validation accuracy: 0.30232558
29 Validation ac